Implementada pantalla principal con menú con opciones
IESAM-DAM/avila-en-tapas pull request #11
Opened 2021-12-15 16:07 UTC by tijanidian

## Description de la tarea

Se trata de implementar la pantalla principal (MainActivity) con un menú de opciones.
La pantalla principal es una actividad que cargará fragmentos según la opción seleccionada. En esta issue no se hará referencia directa al fragmento a cargar pero si tendrá los métodos necesarios para poder cargarlos (replace fragments).
## ¿Cómo se ha implementado?
He creado un nuevo menu para la navegacion entre menus, que esta formado por cuatro botones, haciendo referencia al activity main.

## Keywords

Bottom navegation, fragment
## Screenshots or Video

![Screenshot_1639584102](https://user-images.githubusercontent.com/73607974/146221289-5d2dcd5b-3207-4ecd-8ae3-f01a1bc2db13.png)

## Objetivos

## Criterios de Evaluación

2021-12-16 10:59 UTC, mesteban10 approved these changes
Buena implementación del código, en mi opinión has conseguido lo que pedía la tarea! :)

2021-12-16 15:42 UTC, jmperezra requested changes
La PR está bien comentada pero hay un par de comentarios que deberían resolverse.

2021-12-16 15:42 UTC, jmperezra commented on app/src/main/java/com/jmperezra/avilaentapas/features/main/MainActivity.kt
> +        fragmentTransition.replace(layouyId, fragment)
Tijani, si el layout donde se va a añadir el fragment siempre es el mismo, no hace falta pasarlo por parámetro.

2021-12-16 15:42 UTC, jmperezra commented on app/src/main/res/layout/activity_main.xml
> -        android:layout_width="wrap_content"
¿dónde vas a cargar los fragments?

2021-12-16 17:26 UTC, tijanidian commented on app/src/main/java/com/jmperezra/avilaentapas/features/main/MainActivity.kt
> +        fragmentTransition.replace(layouyId, fragment)
Arreglado:)

2021-12-16 17:33 UTC, tijanidian commented on app/src/main/res/layout/activity_main.xml
> -        android:layout_width="wrap_content"
Solucionado:)

2021-12-16 17:44 UTC, jmperezra requested changes
Solo unos cambios menores ;) Lee los comentarios, si hay algo que no se entienda me dices :)

2021-12-16 17:44 UTC, jmperezra commented on app/src/main/java/com/jmperezra/avilaentapas/features/main/MainActivity.kt
> +        fragmentTransition.replace(idLayout, fragment)
Tenemos que evitar crearnos variables en estos casos:
```suggestion
        fragmentTransition.replace(R.id.container_fragment, fragment)
```

2021-12-16 17:44 UTC, jmperezra commented on app/src/main/res/layout/activity_main.xml
> +            android:layout_height="wrap_content"
Aquí vamos a cargar diferentes fragmentos que tendrán estilos diferentes. Deberíamos permitir que el fragmento que se cargue ocupe todo el espacio disponible. Haz que el fragmento ocupe todo el espacio disponible ;)

2021-12-16 18:00 UTC, tijanidian commented on app/src/main/java/com/jmperezra/avilaentapas/features/main/MainActivity.kt
> +        fragmentTransition.replace(idLayout, fragment)
solucionado

2021-12-16 18:00 UTC, tijanidian commented on app/src/main/res/layout/activity_main.xml
> +            android:layout_height="wrap_content"
solucionado

2021-12-17 11:00 UTC, jmperezra approved these changes
Ok, está bien.

2021-12-17 16:25 UTC, merged