Implementación de listado de eventos vacíos
IESAM-DAM/avila-en-tapas pull request #14
Opened 2021-12-16 16:16 UTC by redondoM20

## Description de la tarea
Implementación de un listado de eventos con un ViewHolder vacío. Además se ha creado un repositorio de eventos con un MockLocalSource 

## ¿Cómo se ha implementado?
En el fragmento agregado a la actividad hay un RecyclerView con un listado de eventos obtenidos a través del ViewModel y gestionado con LiveData y Coroutines

## Keywords

## Screenshots or Video

## Objetivos

## Criterios de Evaluación

2021-12-17 20:46 UTC, tijanidian reviewed
En generar esta muy bien hecha la tarea, te he sugerido unos pequeños cambios :)

2021-12-17 20:46 UTC, tijanidian commented on app/src/main/res/layout/activity_main.xml
>          android:layout_height="wrap_content"
sería mas conveniente poner match_parent en el height

2021-12-17 20:46 UTC, tijanidian commented on app/src/main/res/layout/event_list_fragment.xml
> +        android:layout_margin="10dp"
Usa @dimens para meter los tamaños :)

2021-12-17 20:46 UTC, tijanidian commented on app/src/main/res/layout/view_item_eventlist.xml
> +    android:layout_margin="8dp">
Usa @dimens para meter los tamaños :)

2021-12-17 20:46 UTC, tijanidian commented on app/src/main/res/layout/view_item_eventlist.xml
> +            />
Podrías tabular con ctrl+alt+L así quedaría mas bonito el código

2021-12-20 16:38 UTC, jmperezra requested changes
Hola Marcos, te he dejado varios comentarios que debes repasar y corregir. A modo resumen:

- Debes fijarte en los namings de los id de las vistas, en algunos usas el formato de todo minúsculas separado con guión bajo y en otros usas camelcase. El correcto es el del guión bajo, fíjate en el código de android.
- Hay que añadir Hilt (pregunta si tienes dudas).
- Hay que usar los estilos ya definidos en styles (se crearon el viernes).

@tijanidian debemos mirar la PR con más detalles, se han obviado cosas importantes que no siguen el criterio acordado en clase.

2021-12-20 16:38 UTC, jmperezra commented on app/src/main/java/com/jmperezra/avilaentapas/features/main/MainActivity.kt
> +        replaceFragment(bind.containerFragment.id, EventListFragment.newInstance())
¿por qué cargas el fragment del evento nada más iniciar la actividad?

2021-12-20 16:38 UTC, jmperezra commented on app/src/main/java/com/jmperezra/avilaentapas/features/main/events/data/EventDataRepository.kt
> +class EventDataRepository (private val mockLocalSource: MockLocalSource){
¿puedes añadir Hilt a MockLocalSource?

2021-12-20 16:38 UTC, jmperezra commented on app/src/main/java/com/jmperezra/avilaentapas/features/main/events/domain/EventModel.kt
> +data class EventModel(val id:String, val title:String, val description: String, val start: String, val end: String, val organizer: String, val image: String, val categories: List<CategoryModel>)
¿qué es start? ¿end?

2021-12-20 16:38 UTC, jmperezra commented on app/src/main/java/com/jmperezra/avilaentapas/features/main/events/domain/GetEventsUseCase.kt
> +class GetEventsUseCase (private val repository: EventDataRepository){
¿Puedes añadir Hilt?

2021-12-20 16:38 UTC, jmperezra commented on app/src/main/java/com/jmperezra/avilaentapas/features/main/events/presentation/EventListFragment.kt
> +    private val viewModel: EventListViewModel by lazy {
Debes hacerlo con Hilt

2021-12-20 16:38 UTC, jmperezra commented on app/src/main/java/com/jmperezra/avilaentapas/features/main/events/presentation/EventListFragment.kt
> +        fun newInstance() = EventListFragment()
¿Puedes injectar el fragmento con Hilt?

2021-12-20 16:38 UTC, jmperezra commented on app/src/main/java/com/jmperezra/avilaentapas/features/main/events/presentation/EventListViewModel.kt
> +class EventListViewModel(val getEventsUseCase: GetEventsUseCase) : ViewModel() {
¿Puedes usar Hilt?

2021-12-20 16:38 UTC, jmperezra commented on app/src/main/java/com/jmperezra/avilaentapas/features/main/events/presentation/EventListViewModel.kt
> +                _eventViewState.value = EventViewState(false, it, null)
Genial!

2021-12-20 16:38 UTC, jmperezra commented on app/src/main/java/com/jmperezra/avilaentapas/features/main/events/presentation/EventListViewModel.kt
> +                _eventViewState.value = EventViewState(false, null, Failure.DataError)
Genial!

2021-12-20 16:38 UTC, jmperezra commented on app/src/main/java/com/jmperezra/avilaentapas/features/main/events/presentation/EventListViewModel.kt
> +            val events = getEventsUseCase.execute()
Una propuesta para el código que has puesto aquí:
```
...
   events.fold({eventsSuccess(it)},{eventsError(it)})
...

private fun eventsSuccess(result: Result<List<EventsModel>>){ ... }
private fun eventsError(result: Result<List<EventsModel>>){ ... }
```

2021-12-20 16:38 UTC, jmperezra commented on app/src/main/res/layout/activity_main.xml
>          android:layout_height="wrap_content"
Marcos, revisa los estilos predefinidos en el proyecto (tráete los cambios de develop). Un margen debería usar both_spacing, vertical_spacing o horizontal_spacing.

2021-12-20 16:38 UTC, jmperezra commented on app/src/main/res/layout/event_list_fragment.xml
> +        android:layout_margin="10dp"
Marcos, revisa los estilos predefinidos en el proyecto (tráete los cambios de develop). Un margen debería usar both_spacing, vertical_spacing o horizontal_spacing.

2021-12-20 16:38 UTC, jmperezra commented on app/src/main/res/layout/view_item_eventlist.xml
> +    android:layout_margin="8dp">
Marcos, revisa los estilos predefinidos en el proyecto (tráete los cambios de develop). Un margen debería usar both_spacing, vertical_spacing o horizontal_spacing.

2021-12-20 16:38 UTC, jmperezra commented on app/src/main/res/layout/view_item_eventlist.xml
> +            android:id="@+id/eventImage"
mejor, android:id="logo_event"

2021-12-20 16:38 UTC, jmperezra commented on app/src/main/res/layout/view_item_eventlist.xml
> +                android:id="@+id/eventTitle"
recuerda la convención para los atributos de la vista, fíjate en android:layout_width, android:layout_height.... usan minúsculas separadas por un guión bajo:
android:id="@+id/label_title"

2021-12-20 16:38 UTC, jmperezra commented on app/src/main/res/layout/view_item_eventlist.xml
> +                android:id="@+id/eventStart"
recuerda la convención para los atributos de la vista, fíjate en android:layout_width, android:layout_height.... usan minúsculas separadas por un guión bajo:
android:id="@+id/label_start_date"

2021-12-20 16:38 UTC, jmperezra commented on app/src/main/res/layout/view_item_eventlist.xml
> +                android:id="@+id/eventEnd"
recuerda la convención para los atributos de la vista, fíjate en android:layout_width, android:layout_height.... usan minúsculas separadas por un guión bajo:
android:id="@+id/label_end_date"

2021-12-20 16:38 UTC, jmperezra commented on app/src/main/res/layout/view_item_eventlist.xml
> +                android:id="@+id/eventOrganizer"
recuerda la convención para los atributos de la vista, fíjate en android:layout_width, android:layout_height.... usan minúsculas separadas por un guión bajo:
android:id="@+id/label_organizer"

2021-12-20 16:38 UTC, jmperezra commented on build.gradle
> +        classpath 'com.google.dagger:hilt-android-gradle-plugin:2.38.1'
cuidado con esto, ¿qué pasa si tus compañeros no se han actualizado?

2022-01-11 19:24 UTC, jmperezra requested changes
En líneas generales la PR está bastante bien, me gusta mucho la parte de Coroutines, LiveData (PSP) y el planteamiento de la UI (PMDM). Sólo te he puesto unos comentarios menores.

2022-01-11 19:24 UTC, jmperezra commented on app/src/main/java/com/jmperezra/avilaentapas/features/events/presentation/EventListViewModel.kt
> +            events.fold({eventSuccess(it)},{eventFailure(it)})
Está muy bien Marcos, te dejo otra propuesta:
```
getEventsUseCase.execute().fold( .... )
```

2022-01-11 19:24 UTC, jmperezra commented on app/src/main/java/com/jmperezra/avilaentapas/features/events/presentation/EventViewState.kt
> +data class EventViewState(val isLoading: Boolean, val eventModel: List<EventModel>?, val failure: Throwable?)
Por convenio, vamos a usar EventUIState

2022-01-11 19:24 UTC, jmperezra commented on app/src/main/res/layout/event_list_fragment.xml
> +        android:padding="10dp"
El padding, vamos a dejarlo que lo haga el ViewHolder, recuerda, que para los espacios verticales u horizontales usamos space_vertical, etc.

2022-01-11 19:24 UTC, jmperezra commented on build.gradle
> +        classpath 'com.google.dagger:hilt-android-gradle-plugin:2.38.1'
Recuerda no actualizar librerías hasta que la tarea no sea esa, debemos centrarnos en la feature y lo demás, ya se hará ;)

2022-01-13 15:23 UTC, jmperezra approved these changes
👍

2022-01-13 15:41 UTC, tijanidian approved these changes
Buen trabajo, has cumplido lo que de pedía :)

2022-01-13 16:32 UTC, merged