Eliminación de votos de usuario.
IESAM-DAM/avila-en-tapas pull request #183
Opened 2022-03-09 17:33 UTC by mesteban10

## Description de la tarea

Flujo completo de datos para eliminar una votación en Firebase.

## ¿Cómo se ha implementado?
- Se implementa método 'deleteUserVote()' en la interfaz 'UserVoteRemoteSource'.
- En la clase 'UserVoteDbRemoteSource'  se implementa el método de la interfaz para eliminar los datos de Firebase.
- Se implementa método 'deleteUserVote()' en la interfaz 'UserVoteRepository'.
- En la clase 'UserVoteDataRepository' se implementa el método 'deleteUserVote()' que llama a 'UserVoteRemoteSource' para elimar el nodo de la tapa indicada.
- Se crea el Caso de Uso 'DeleteUserVoteUseCase' con el método 'execute()'.
- En la CustomView  RatingBarView, se indica que si la estrella 1 está marcada y se vuelve a pulsar, se establece el valor 0.
- En 'UserVoteDialog' en la función 'renderUserTapaVote()' cuando se pulsa el botón votar se establece la siguiente lógica: 
 `-` Si el valor del RatingBar es distinto de 0, se guarda la votación en Firebase.
 `-` Si el valor es 0 , se elimina la votación en firebase llamando al ViewModel que implementa el caso de uso  'DeleteUserVoteUseCase'.
Otros:
- Se elimina el nulo del valor del Modelo 'UserReviewModel', se pone por defecto el valor 0.

## Keywords

Firebase, ViewModel, CustomView. 
## Screenshots or Video

https://user-images.githubusercontent.com/91340537/157496177-c73c0871-cb78-4425-b8c4-0a4da3dbb1b0.mp4

2022-03-09 19:24 UTC, jmperezra requested changes
Hola María, sólo unos cambios sobre el onFailure y la gestión en local de votos. Como te he comentado es más sencillo para nosotros no tratar nada de votos locales, así que todo lo referente a esto lo eliminamos y sólo usamos Remote :)

2022-03-09 19:24 UTC, jmperezra commented on app/src/main/java/com/jmperezra/avilaentapas/features/reviews/data/UserVoteDataRepository.kt
> +            return Result.success(false)
María, si se produce un error, no podemos devolver un success. Devolvemos lo que recibamos del datasource. Te sobra el onFailure.

2022-03-09 19:24 UTC, jmperezra commented on app/src/main/java/com/jmperezra/avilaentapas/features/reviews/data/local/db/UserVoteDao.kt
> +    fun deleteUserReview(tapaId: String)
No hace falta eliminar en local. Para votos no vamos a trabajar en local, es decir, si no tiene red, el usuario no podrá votar. Es que si no, se nos va a hacer muy complejo estar coordinando los votos en local y en red (imaginate que vota desde otro móvil)

2022-03-09 20:02 UTC, mesteban10 commented on app/src/main/java/com/jmperezra/avilaentapas/features/reviews/data/UserVoteDataRepository.kt
> +            return Result.success(false)
Ya está corregido 👍

2022-03-09 20:02 UTC, mesteban10 commented on app/src/main/java/com/jmperezra/avilaentapas/features/reviews/data/local/db/UserVoteDao.kt
> +    fun deleteUserReview(tapaId: String)
He subido los cambios eliminando toda la parte de local de votaciones 👍

2022-03-10 10:40 UTC, jmperezra approved these changes
Genial María, vamos a unirlo en develop y reviso la integración junto con el resto del código.

2022-03-10 10:40 UTC, merged