Sp02 Toolbar collapse
IESAM-DAM/avila-en-tapas pull request #42
Opened 2022-01-13 15:50 UTC by tijanidian

## Description de la tarea

Se pide añadir la Toolbar al activity_main. Además, la Toolbar añadida deberá ocultarse según hacemos up-scroll, y mostrarse cuando hacemos down-scroll.
## ¿Cómo se ha implementado?
He usado CoordinatorLayout que proporciona un nivel adicional de control sobre los eventos táctiles. y asi hace el efecto de desaparecer de la Toolbar

## Keywords
CoordinatorLayout, Toolbar

## Screenshots or Video

![Screenshot_1642087626](https://user-images.githubusercontent.com/73607974/149362347-b223e8a9-b72f-4b38-8623-e3469d8acbb0.png)

![Screenshot_1642087629](https://user-images.githubusercontent.com/73607974/149362364-1a3c4c03-8637-4373-a022-613101a020a3.png)

## Objetivos

## Criterios de Evaluación

2022-01-13 16:45 UTC, mesteban10 requested changes
Te he dejado algunos comentarios y algunas propuestas de cambio que pueden mejorar tu código y la funcionalidad de este. Revísalos a ver que te parecen :)

2022-01-13 16:45 UTC, mesteban10 commented on app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/appbarLayout"
El naming del id debería ir con underscore, por ejemplo podrías poner: "app_bar_layout".

2022-01-13 16:45 UTC, mesteban10 commented on app/src/main/res/menu/main_menu.xml
> +        app:showAsAction="never" />
En la propiedad showAsAction, debería de ir always como en el item anterior, ya que si pones never nunca aparecerá este item en la toolbar.

2022-01-13 16:45 UTC, mesteban10 commented on app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/constraintLayout"
Aquí pondría un nombre más específico al identificador, como navigation_menu.

2022-01-13 16:45 UTC, mesteban10 commented on app/src/main/java/com/jmperezra/avilaentapas/features/main/MainActivity.kt
> +            else -> super.onOptionsItemSelected(item)
Te falta añadir la acción al botón botón del menú "action_settings".

2022-01-13 16:45 UTC, mesteban10 commented on app/src/main/res/layout/activity_main.xml
> +    <com.google.android.material.appbar.AppBarLayout
En mi opinión, esta parte en la que creas la toolbar, la externalizaría a otro fichero y después le añadiría a esta vista de la actividad principal.
Así si volvemos ha hacer uso de la toolbar, evitamos la duplicación de código :)

2022-01-13 19:01 UTC, tijanidian commented on app/src/main/res/menu/main_menu.xml
> +        app:showAsAction="never" />
Poniendo "never" y sin introducir un "icon" consigo mostras los 3 puntos verticales tan característicos de Android :)

2022-01-13 19:02 UTC, tijanidian commented on app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/constraintLayout"
Resuelto, de tantos cambios lo puse mal  otra vez :)

2022-01-13 19:02 UTC, tijanidian commented on app/src/main/java/com/jmperezra/avilaentapas/features/main/MainActivity.kt
> +            else -> super.onOptionsItemSelected(item)
Solucionado

2022-01-13 19:04 UTC, tijanidian commented on app/src/main/res/layout/activity_main.xml
> +    <com.google.android.material.appbar.AppBarLayout
AppBarLoyout tiene que ir con el padre coordinatorlayout para así conseguir la animación de la Toolbar

2022-01-14 17:45 UTC, closed without merging

2022-01-14 17:46 UTC, tijanidian commented
Me ha dado un error con la animación