Sp02 Event View item list
IESAM-DAM/avila-en-tapas pull request #44
Opened 2022-01-13 17:42 UTC by tijanidian

## Description de la tarea

Se pide diseñar el item del evento que se muestra en el listado de eventos.
## ¿Cómo se ha implementado?
He creado un nuevo recurso view_event_list_item con un card view 

## Keywords

cardview, constraintLayout, dimens
## Screenshots or Video

![captura](https://user-images.githubusercontent.com/73607974/149380545-84c50006-747e-4e9d-9136-f59cd434343c.PNG)

## Objetivos

## Criterios de Evaluación

2022-01-14 18:22 UTC, JavierManc commented on app/src/main/res/layout/view_event_list_item.xml
> +            android:id="@+id/event_start_date"
En los naming no hace falta que pongas event al inicio, simplemente podrías poner "text_start_date"

2022-01-14 18:23 UTC, JavierManc approved these changes
Te he dejado un comentario sobre los naming, pero lo demás está bien.

2022-01-19 16:21 UTC, jmperezra requested changes
@tijanidian hay cosas que revisar: namings.

2022-01-19 16:21 UTC, jmperezra commented on app/src/main/res/layout/view_event_list_item.xml
> +            android:id="@+id/event_start_date"
mejor, label_start_date

2022-01-19 16:21 UTC, jmperezra commented on app/src/main/res/layout/view_event_list_item.xml
> +            android:id="@+id/event_organicer"
label_management

2022-01-19 16:21 UTC, jmperezra commented on app/src/main/res/layout/view_event_list_item.xml
> +            android:text="@string/app_name"
Esto??

2022-01-19 17:10 UTC, tijanidian commented on app/src/main/res/layout/view_event_list_item.xml
> +            android:id="@+id/event_start_date"
Arreglado

2022-01-19 17:32 UTC, tijanidian commented on app/src/main/res/layout/view_event_list_item.xml
> +            android:id="@+id/event_end_date"
Arreglado

2022-01-20 15:20 UTC, jmperezra approved these changes
👍

2022-01-20 17:40 UTC, merged