Detalle del Evento (UI-Domain)
IESAM-DAM/avila-en-tapas pull request #53
Opened 2022-01-14 19:09 UTC by redondoM20

## Description de la tarea
Desarrollo de la parte del detalle del evento

## ¿Cómo se ha implementado?
Se ha implementado la actividad con la vista y el viewModel correspondientes además de el caso de uso y una interfaz de repositorio

## Keywords

## Screenshots or Video

## Objetivos

## Criterios de Evaluación

2022-01-17 17:32 UTC, mesteban10 requested changes
En general el código está bien, te he dejado algunos comentarios para que los revieses. Además te falta implementar la acción del botón share en  "DatailActivityEvent", revísalo :)

2022-01-17 17:32 UTC, mesteban10 commented on app/src/main/java/com/jmperezra/avilaentapas/features/events/data/EventDataRepository.kt
>  import javax.inject.Inject
Este import no debería ir aquí!

2022-01-17 17:32 UTC, mesteban10 commented on app/src/main/java/com/jmperezra/avilaentapas/features/events/presentation/DetailEventActivity.kt
> +        supportActionBar?.title = ""
Si la toolbar no va a tener título, puedes suprimir esta línea!

2022-01-17 17:32 UTC, mesteban10 commented on app/src/main/res/layout/activity_detail_event.xml
> +            android:id="@+id/main_bar"
Cambiaría el naming del id, ya que no es la toolbar principal del proyecto. La nombraría "datail_event_bar", por ejemplo.

2022-01-17 17:32 UTC, mesteban10 commented on app/src/main/res/layout/activity_detail_event.xml
> +            tools:text="Avila en tapas en 2021"
Crea un @string, en vez de meter el texto literal en la vista :)

2022-01-17 17:32 UTC, mesteban10 commented on app/src/main/res/layout/activity_detail_event.xml
> +            tools:text="Concurso de tapas en Ávila donde se premia la mejor tapa elaborada por bares de la ciudad"
Crea un @string, en vez de meter el texto literal en la vista :)

2022-01-17 17:32 UTC, mesteban10 commented on app/src/main/res/layout/activity_detail_event.xml
> +            tools:text="Fechas"
Crea un @string, en vez de meter el texto literal en la vista :)

2022-01-17 17:32 UTC, mesteban10 commented on app/src/main/res/layout/activity_detail_event.xml
> +                tools:text="Fecha de inicio: "/>
Crea un @string, en vez de meter el texto literal en la vista :)

2022-01-17 17:32 UTC, mesteban10 commented on app/src/main/res/layout/activity_detail_event.xml
> +                tools:text="01/07/2021"/>
Crea un @string, en vez de meter el texto literal en la vista :)

2022-01-17 17:32 UTC, mesteban10 commented on app/src/main/res/layout/activity_detail_event.xml
> +                tools:text="Fecha de fin: "/>
Crea un @string, en vez de meter el texto literal en la vista :)

2022-01-17 17:32 UTC, mesteban10 commented on app/src/main/res/layout/activity_detail_event.xml
> +                tools:text="05/07/2021"/>
Crea un @string, en vez de meter el texto literal en la vista :)

2022-01-17 17:32 UTC, mesteban10 commented on app/src/main/res/layout/activity_detail_event.xml
> +                tools:text="Díptico del evento"/>
Crea un @string, en vez de meter el texto literal en la vista :)

2022-01-17 17:32 UTC, mesteban10 commented on app/src/main/res/layout/activity_detail_event.xml
> +                tools:text="Organizador: "/>
Crea un @string, en vez de meter el texto literal en la vista :)

2022-01-17 17:32 UTC, mesteban10 commented on app/src/main/res/layout/activity_detail_event.xml
> +                tools:text="Ayuntamiento de Ávila"/>
Crea un @string, en vez de meter el texto literal en la vista :)

2022-01-17 17:32 UTC, mesteban10 commented on app/src/main/res/layout/activity_detail_event.xml
> +                tools:text="Más información : "/>
Crea un @string, en vez de meter el texto literal en la vista :)

2022-01-17 17:32 UTC, mesteban10 commented on app/src/main/res/layout/activity_detail_event.xml
> +                tools:text="Web oficial del evento"/>
Crea un @string, en vez de meter el texto literal en la vista :)

2022-01-17 17:32 UTC, mesteban10 commented on app/src/main/java/com/jmperezra/avilaentapas/features/events/presentation/DetailEventActivity.kt
> +
Te falta la implementación del botón share de la toolbar aquí en la actividad.

2022-01-19 16:30 UTC, jmperezra requested changes
Hay cosas que debemos prestar atención como los namings y el contenido de la PR. Estás haciendo una PR visual y sería de gran utilidad ver cómo ha quedado la pantalla. Sin esta información es complicado hacerse una idea (Ver qué se pedía y ver el resultado).

2022-01-19 16:30 UTC, jmperezra commented on app/src/main/java/com/jmperezra/avilaentapas/features/events/presentation/DetailEventActivity.kt
> +        supportActionBar?.title = ""
Eso es, el título se establecerá de forma dinámica cuando se obtengan los datos.

2022-01-19 16:30 UTC, jmperezra commented on app/src/main/java/com/jmperezra/avilaentapas/features/events/presentation/DetailEventActivity.kt
> +
Aquí debes usar el UiState visto en clase.

2022-01-19 16:30 UTC, jmperezra commented on app/src/main/java/com/jmperezra/avilaentapas/features/events/presentation/EventListViewModel.kt
> +        _Events_UIState.value = EventsUIState(false, items, null)
Por favor, usa el nuevo UiState

2022-01-19 16:30 UTC, jmperezra commented on app/src/main/java/com/jmperezra/avilaentapas/features/events/presentation/EventUIState.kt
> +data class EventUIState(
Por favor, usa el nuevo UiState

2022-01-19 16:30 UTC, jmperezra commented on app/src/main/res/layout/activity_detail_event.xml
> +            android:id="@+id/event_title"
label_title

2022-01-19 16:30 UTC, jmperezra commented on app/src/main/res/layout/activity_detail_event.xml
> +            tools:text="Avila en tapas en 2021"
En este caso podemos usarlo de forma directa porque está asingado a tools:text y no a android:text :)

2022-01-19 16:30 UTC, jmperezra commented on app/src/main/res/layout/activity_detail_event.xml
> +            android:id="@+id/dates"
hace falta este id?

2022-01-19 16:30 UTC, jmperezra commented on app/src/main/res/layout/activity_detail_event.xml
> +                android:id="@+id/event_date_title_start"
label_date_title_start

2022-01-19 16:30 UTC, jmperezra commented on app/src/main/res/layout/activity_detail_event.xml
> +                android:id="@+id/event_date_start"
label_lo_que_sea

2022-01-19 16:30 UTC, jmperezra commented on app/src/main/res/layout/activity_detail_event.xml
> +                android:id="@+id/event_date_title_end"
label_lo_que_sea

2022-01-19 16:30 UTC, jmperezra commented on app/src/main/res/layout/activity_detail_event.xml
> +                android:id="@+id/event_date_end"
label_lo_que_sea

2022-01-19 16:30 UTC, jmperezra commented on app/src/main/res/layout/activity_detail_event.xml
> +            android:id="@+id/event_files"
label_XXXX

2022-01-20 15:30 UTC, redondoM20 commented on app/src/main/res/layout/activity_detail_event.xml
> +            android:id="@+id/dates"
Lo utilizo para poder situar el event_files justo debajo

2022-01-20 17:25 UTC, mesteban10 requested changes

2022-01-20 17:25 UTC, mesteban10 commented on app/src/main/java/com/jmperezra/avilaentapas/features/events/presentation/EventsListFragment.kt
> +
Te falta la implementación del observador, para que puedan ser recogidos y mostrados los datos.

2022-01-20 22:06 UTC, mesteban10 requested changes
Creo que te falta implementar el observer en la Actividad del detalle del evento, revísalo :)

2022-01-21 16:47 UTC, jmperezra requested changes
Te hemos dejado unos comentarios

2022-01-21 16:47 UTC, jmperezra commented on app/src/main/res/layout/activity_detail_event.xml
> +    <androidx.appcompat.widget.Toolbar
Marcos, aquí vendría hacer mejor un include de la toolbar que ya está hecha.

2022-01-21 16:47 UTC, jmperezra commented on app/src/main/res/layout/activity_detail_event.xml
> +        android:layout_width="match_parent"
match_parent¿? habrá que poner un tamaño fijo, puedes probar con 64dpx64dp, mételos en dimens

2022-01-21 18:51 UTC, mesteban10 approved these changes

2022-01-27 19:11 UTC, jmperezra approved these changes
Bien, está bastante bien. Nos va a tocar modificar cosas de la UI, tenemos que crear estilos en vez de ir metiendo color a color los textos, etc.
👍

2022-01-27 19:14 UTC, merged