Efecto de la toolbar collapse
IESAM-DAM/avila-en-tapas pull request #60
Opened 2022-01-19 16:24 UTC by tijanidian

## Description de la tarea

Se pide añadir la Toolbar al activity_main. Además, la Toolbar añadida deberá ocultarse según hacemos up-scroll, y mostrarse cuando hacemos down-scroll.
## ¿Cómo se ha implementado?

## Keywords
Constraintlayout, Toolbar, Coordinatorlayout, Scroll

## Screenshots or Video

https://user-images.githubusercontent.com/73607974/150172256-cafde76e-64d6-4ded-8234-58243eeaf957.mp4

## Objetivos

2022-01-19 16:51 UTC, mesteban10 requested changes
El código esta muy bien, te he dejado dos comentarios para que cambies algunas cosas, revísalo :)

2022-01-19 16:51 UTC, mesteban10 commented on app/src/main/java/com/jmperezra/avilaentapas/features/main/MainActivity.kt
> +        setSupportActionBar(binding.mainBar)
Elimina este método, ya que estás estableciendo la misma toolbar dos veces en la actividad (en el método "setUpToolbar()" duplicas este fragmento de código).

2022-01-19 16:51 UTC, mesteban10 commented on app/src/main/java/com/jmperezra/avilaentapas/features/main/MainActivity.kt
> +            }
Añade la acción para el item accion_settings del menú, a pesar de que no tenga ninguna acción todavía puedes dejarla vacía :)

2022-01-19 17:41 UTC, tijanidian commented on app/src/main/java/com/jmperezra/avilaentapas/features/main/MainActivity.kt
> +        setSupportActionBar(binding.mainBar)
Arreglado

2022-01-19 17:41 UTC, tijanidian commented on app/src/main/java/com/jmperezra/avilaentapas/features/main/MainActivity.kt
> +            }
Esto lo ha implementado otro compañero :)

2022-01-19 18:14 UTC, mesteban10 approved these changes

2022-01-21 16:48 UTC, jmperezra approved these changes

2022-01-21 16:49 UTC, merged