Integración Listado de Eventos en la estructura del Main
IESAM-DAM/avila-en-tapas pull request #61
Opened 2022-01-19 16:44 UTC by tijanidian

## Description de la tarea

Se pide intregar el Fragment del listado de Eventos en la estructura del Main (menú)
## ¿Cómo se ha implementado?

He creado una funcion loadEvent para cargar en fragmento de evento al hacer click en el bottomnavigation

## Keywords
bottomnavigation, fragments, naming

## Screenshots or Video

https://user-images.githubusercontent.com/73607974/150175392-2c7198e2-0c49-4d0e-a03f-5bf252b606c3.mp4

2022-01-20 15:23 UTC, redondoM20 approved these changes
En general esta muy hecha 👌

2022-01-20 15:31 UTC, jmperezra requested changes
Coincido con el comentario de @redondoM20 , revísalos please.

2022-01-20 15:50 UTC, tijanidian commented on app/src/main/java/com/jmperezra/avilaentapas/features/main/MainActivity.kt
>          fragmentTransition.addToBackStack(null)
Bien visto, se me ha pasado :)

2022-01-21 16:49 UTC, jmperezra approved these changes
Ok 👍

2022-01-21 16:52 UTC, merged