Implementada actividad de detalle de una tapa
IESAM-DAM/avila-en-tapas pull request #62
Opened 2022-01-19 16:49 UTC by JavierManc

## Description de la tarea

Se ha implementado una actividad con un ViewModel, un caso de uso para la obtención de una tapa en específico y una vista en la que se muestran todos los datos. Además, a la vista se le ha añadido una toolbar con un menú.

## ¿Cómo se ha implementado?

En la actividad se recogen los datos mediante el ViewModel (el cual funciona con coroutines) y desde esta,  se dibujan los datos obtenidos en la vista, en esta se muestra el nombre del bar, el nombre de la tapa, la descripción de la tapa, los alérgenos y otro apartado que identifica si esta tapa es vegetariana o vegana.
Además, se ha implementado hilt a esta actividad.

## Keywords

Activity, ViewModel, Coroutines, Toolbar, Menu, Observers, View, UseCase, Hilt

## Screenshots or Video

https://user-images.githubusercontent.com/73607959/150176268-8eb9c494-b9a4-4d08-9289-ff9d56fd1d68.mp4

2022-01-20 15:28 UTC, tijanidian approved these changes
¿Por qué usas imágenes en formato png ? Eso va a hacer que la Apk de la aplicación pese demasiado, podrías usar imagen con formato svg

2022-01-20 15:28 UTC, tijanidian commented on app/src/main/res/layout/view_tapa_detail.xml
> +            android:id="@+id/text_bar_name"
Cambia text por label, por ejemplo, "label_bar name"

2022-01-20 15:28 UTC, tijanidian commented on app/src/main/res/layout/view_tapa_detail.xml
> +            android:id="@+id/text_tapa_name"
Cambia text por label, por ejemplo, "label_tapa name"

2022-01-20 15:28 UTC, tijanidian commented on app/src/main/res/layout/view_tapa_detail.xml
> +            android:id="@+id/text_tapa_ingredients"
Cambia text por label

2022-01-20 15:28 UTC, tijanidian commented on app/src/main/res/layout/view_tapa_detail.xml
> +            android:id="@+id/text_tapa_allergens"
Cambia text por label

2022-01-20 16:12 UTC, jmperezra requested changes
@JavierManc la PR está genial, perfectamente documentada, se entiende perfectamente lo que has hecho. Te he puesto unos comentarios con la finalidad de mejorar la legibilidad del código, es decir, que se entienda bien por alguien que no lo ha programado. Revisa lo del Gridlayout, está muy bien resuelto y has aprendido añadir vistas de forma dinámica, eso es está genial.

2022-01-20 16:12 UTC, jmperezra commented on app/src/main/res/values/strings.xml
> +    <string name="share_image">Share_image</string>
menu_share y ponlo luego en español: Compartir
menu_favorite: Favoritos

2022-01-20 19:08 UTC, JavierManc commented on app/src/main/java/com/jmperezra/avilaentapas/features/tapas/presentation/TapaDetailActivity.kt
> +    @SuppressLint("UseCompatLoadingForDrawables")
Esto me lo pide al hacer el "getDrawable" para obtener el color

2022-01-20 19:10 UTC, JavierManc commented on app/src/main/java/com/jmperezra/avilaentapas/features/tapas/presentation/TapaDetailActivity.kt
> +        val layoutParams = LinearLayout.LayoutParams(150, 150)
Esto al final lo dejaré de esta manera hasta que encuentre otra manera mejor de ponerlo, ya que de la manera que sea hay que ponerle unas dimensiones, con un WrapContent no funciona.

2022-01-21 18:38 UTC, jmperezra approved these changes
👍

2022-01-21 18:38 UTC, merged