Añadir un widget para la carga de datos para Detalle de Evento
IESAM-DAM/avila-en-tapas pull request #69
Opened 2022-01-20 18:01 UTC by tijanidian

## Description de la tarea
Se pide desarrollar una feature que permita mostrar un spinner (ProgressBar) cuando estamos cargando datos y ocultarlo una vez obtenido los datos.

## ¿Cómo se ha implementado?
Se pide desarrollar una feature que permita mostrar un spinner (ProgressBar) cuando estamos cargando datos y ocultarlo una vez obtenido los datos.

 Añadir una vista: view_loading_progress donde tenga un progressbar indeterminado (por defecto GONE).
 El Main Activity añadirá la vista view_loading_progress (include).
 Habrá dos métodos en el MainActivity para mostrar u ocultar el progressbar.
 Se prueba la funcionalidad.

## Keywords

Fragment, xml, progressbar,
## Screenshots or Video

https://user-images.githubusercontent.com/73607974/150395512-5bb826c2-22b7-4086-9788-9305e26b23c9.mp4

2022-01-21 16:24 UTC, JavierManc requested changes
Te he dejado unos comentarios sobre el código, revísalos ya que aunque la aplicación funcione creo que has cambiado cosas que estaban bien, o has puesto código de más en algún apartado.

2022-01-21 16:24 UTC, JavierManc commented on app/src/main/java/com/jmperezra/avilaentapas/features/events/presentation/EventsListFragment.kt
> +    private val viewModel =
¿Por que has quitado el by viewModels?, creo que estaba mejor antes utilizando hilt

2022-01-21 16:24 UTC, JavierManc commented on app/src/main/java/com/jmperezra/avilaentapas/features/main/MainActivity.kt
> +    companion object {
¿Por qué creas este companion object en el MainActivity?, ¿no debería ir en el fragmento?

2022-01-21 16:24 UTC, JavierManc commented on app/src/main/java/com/jmperezra/avilaentapas/features/events/presentation/EventListViewModel.kt
> +            delay(3000)
El delay yo creo que es mejor utilizarlo solo para probar pero no subirlo al proyecto.

2022-01-21 16:38 UTC, tijanidian commented on app/src/main/java/com/jmperezra/avilaentapas/features/events/presentation/EventListViewModel.kt
> +            delay(3000)
Se he ha ido, solucionado.

2022-01-21 16:38 UTC, tijanidian commented on app/src/main/java/com/jmperezra/avilaentapas/features/main/MainActivity.kt
> +    companion object {
Se he ha ido, solucionado.

2022-01-21 16:38 UTC, tijanidian commented on app/src/main/java/com/jmperezra/avilaentapas/features/events/presentation/EventsListFragment.kt
> +    private val viewModel =
Bien visto, arreglado.

2022-01-21 16:52 UTC, jmperezra approved these changes
Sólo un comentario, eliminar los comentarios je je. En cuanto lo hagas, puedes hacer el merge. Por otro lado, cuidado con el formateo que has tocado una clase que no deberías TapasFragment

2022-01-21 16:52 UTC, jmperezra commented on app/src/main/java/com/jmperezra/avilaentapas/features/events/presentation/EventsListFragment.kt
> +   /*     EventListViewModel(GetEventsUseCase(EventDataRepository(MockLocalSource())))*/
Quita esto si no se está usando ;)

2022-01-21 16:54 UTC, tijanidian commented on app/src/main/java/com/jmperezra/avilaentapas/features/events/presentation/EventsListFragment.kt
> +   /*     EventListViewModel(GetEventsUseCase(EventDataRepository(MockLocalSource())))*/
Solucionado

2022-01-21 17:52 UTC, JavierManc requested changes
Creo que has modificado mal los cambios, mira los comentarios que te he dejado

2022-01-21 17:52 UTC, JavierManc commented on app/src/main/java/com/jmperezra/avilaentapas/features/events/presentation/EventsListFragment.kt
> +    companion object {
Has duplicado este companion object, creo que deberías quitar ambos

2022-01-21 17:52 UTC, JavierManc commented on app/src/main/java/com/jmperezra/avilaentapas/features/events/presentation/EventsListFragment.kt
> -        viewModel.loadEvents()
Has eliminado esta función, crees que el codigo funciona bien sin esta línea?

2022-01-21 19:12 UTC, tijanidian commented on app/src/main/java/com/jmperezra/avilaentapas/features/events/presentation/EventsListFragment.kt
> +    companion object {
listo

2022-01-21 19:13 UTC, tijanidian commented on app/src/main/java/com/jmperezra/avilaentapas/features/events/presentation/EventsListFragment.kt
> -        viewModel.loadEvents()
Arreglado

2022-01-27 15:07 UTC, JavierManc approved these changes
Todo correcto, puedes hacer el merge.

2022-01-27 15:16 UTC, merged