Inplementación de estilos y tema de la aplicación.
IESAM-DAM/avila-en-tapas pull request #7
Opened 2021-12-15 15:11 UTC by mesteban10

## Description de la tarea

Se añaden estilos y tema de la aplicación mediante la implementación de la paleta de colores adjuntada.

## ¿Cómo se ha implementado?

La implementación se ha realizado de la siguiente forma:
 - Se han implementado en la carpeta 'res' , donde encontramos los recursos usados por la aplicación, los colores necesarios y 
se ha declarado el tema con estos colores. El tema ha sido declarado con 'NoActionBar', para eliminar este.
- Se ha declarado el tema en el AndroidManifest.
## Keywords

Theme, colors, AndroidManifest, NoActionBar, style, resources, xml

## Screenshots or Video

## Objetivos

## Criterios de Evaluación

2021-12-15 15:17 UTC, jmperezra requested changes
Hola María, ¿no te falta algo? ¿Cómo sabe Android que tiene que coger tu tema?

2021-12-16 15:26 UTC, redondoM20 approved these changes

2021-12-16 15:38 UTC, jmperezra approved these changes
👍

2021-12-16 15:49 UTC, JavierManc approved these changes
Todo correcto ;)

2021-12-16 16:11 UTC, merged