BottomSheet implementado al listado de tapas de MyRating.
IESAM-DAM/avila-en-tapas pull request #81
Opened 2022-01-27 19:36 UTC by mesteban10

## Description de la tarea

Se incorpora el BottomSheet al listado de tapas de la parte de Votaciones.
Al pulsar en un item del listado, en el BottomSheet se muestran los datos de esa tapa y un RatingBar para poder votarla.
Tendremos también dos botones, uno de Votar y otro de cancelar la operación, el cual al pulsarle cierra el ButtomSheet dejándonos visualizar por completo el listado.

## ¿Cómo se ha implementado?
Mediante el uso de la arquitectura MVVM:
- Se han modificado los datos Mock para poder obtener los datos de una tapa mediante su id. A su vez para llevar a cabo esta implementación, se han modificado los repositorios (MyRatingDataDepository y MyRatingRepository), implementando la función para obtener la tapa por su id.
- Se ha creado un nuevo caso de uso para obtener la tapa por su id.
- Se ha creado el ViewModel para el nuevo caso de uso.
- En el fragmento del listado (MyRatingFragment), se implementa una función que recoge el id del item pulsado mediante el adaptador. Esta función crea una instancia para enviarla al BottomSheet y a su vez lo muestra.
- En el BottomSheet se recogen los datos del ViewModel y el id de la tapa y se pintan.
- También se ha creado una nueva vista para el BottomSheet.

Otros:
- Se ha añadido una nueva librería para poder modificar el RatingBar, creada por Iván Arcuschin, que me permite implementar espacio entre las estrellas del RatingBar.
Fuente de información: https://github.com/FlyingPumba/SimpleRatingBar

## Keywords

## Screenshots or Video

https://user-images.githubusercontent.com/91340537/151430519-93846089-0b3b-425b-a9bc-d25f4e2e2de8.mp4

2022-01-28 15:22 UTC, tijanidian approved these changes
Te he sugerido unos cambios menores, pero has complico con la tarea que se pedía :)

2022-01-28 15:22 UTC, tijanidian commented on app/src/main/java/com/jmperezra/avilaentapas/features/myratings/presentation/MyRatingsViewHolder.kt
> +            bind.labelMyRating.text = "--"
Yo no metería texto a pelo

2022-01-28 15:22 UTC, tijanidian commented on app/src/main/res/layout/myratings_bottom_sheet.xml
> +            android:id="@+id/myratings_tapa_title"
podrias cambiar el id por "label", por ejemplo:"label_tapa_title"

2022-01-28 15:22 UTC, tijanidian commented on app/src/main/res/layout/myratings_bottom_sheet.xml
> +            android:id="@+id/myratings_bar_name"
podrias cambiar el id por "label", por ejemplo:"label_tapa_name"

2022-01-28 15:22 UTC, tijanidian commented on app/src/main/res/layout/view_myrating_bottom_sheet.xml
> +                android:textSize="15sp"
puedes utlizar @dimens

2022-01-31 13:26 UTC, mesteban10 commented on app/src/main/java/com/jmperezra/avilaentapas/features/myratings/presentation/MyRatingsViewHolder.kt
> +            bind.labelMyRating.text = "--"
Modificado :)

2022-01-31 13:27 UTC, mesteban10 commented on app/src/main/res/layout/myratings_bottom_sheet.xml
> +            android:id="@+id/myratings_tapa_title"
He eliminado este archivo, ya que lo tengo en "view_myratings_bottom_sheet"

2022-01-31 13:28 UTC, mesteban10 commented on app/src/main/res/layout/view_myrating_bottom_sheet.xml
> +                android:textSize="15sp"
Ya lo he modificado 👍

2022-02-04 18:28 UTC, mesteban10 commented on app/src/main/res/layout/view_myratings_item.xml
> +            android:layout_height="200dp"
Introduzco directamente el valor porque aún esta por definir la vista definitiva.

2022-02-04 18:44 UTC, tijanidian approved these changes
Te he puesto un comentario pequeño, pero todo bien

2022-02-04 18:44 UTC, tijanidian commented on app/src/main/java/com/jmperezra/avilaentapas/features/ratings/data/remote/RatingDbRemoteSource.kt
> +                Log.d("@dev", "Error:$ex")
Puedes quitar ese Log.d :)

2022-02-04 18:48 UTC, jmperezra requested changes
La PR está bastante bien, quizás muy larga, debemos hacerla más pequeña la próxima vez ;)
El diseño está muy bien, creo que te desenvuelves bien con la UI, espero verlo consolidado en la PR del diseño tipo Grid.
La parte de Firebase también está bien y la de Room, aunque es una cosa muy sencillita y apenas he podido ver relaciones.
El objetivo de la documentación está superado con creces.

2022-02-04 18:48 UTC, jmperezra commented on app/build.gradle
> +    implementation 'com.google.android.material:material:1.6.0-alpha02'
Esta librería ya está añadida más arriba.

2022-02-04 18:48 UTC, jmperezra commented on app/build.gradle
> +    implementation 'com.iarcuschin:simpleratingbar:0.1.5'
Esta implementarion está duplicado.

2022-02-04 19:01 UTC, mesteban10 commented on app/src/main/java/com/jmperezra/avilaentapas/features/ratings/data/remote/RatingDbRemoteSource.kt
> +                Log.d("@dev", "Error:$ex")
Ya esta 👍

2022-02-04 19:01 UTC, mesteban10 commented on app/build.gradle
> +    implementation 'com.google.android.material:material:1.6.0-alpha02'
Ya lo he corregido :)

2022-02-04 19:01 UTC, mesteban10 commented on app/build.gradle
> +    implementation 'com.iarcuschin:simpleratingbar:0.1.5'
Ya he eliminado una de ellas, gracias 👍

2022-02-04 19:15 UTC, jmperezra approved these changes

2022-02-04 19:15 UTC, merged