Flujo completo Listado de Eventos
IESAM-DAM/avila-en-tapas pull request #86
Opened 2022-02-03 17:20 UTC by tijanidian

## Description de la tarea
Se pide realizar el flujo completo de eventos. La lógica será:

 En el listado se piden los datos a Firebase y se almacenan en Room.
 Ajustar al diseño.

## ¿Cómo se ha implementado?

He empleado Room con Firebase para poder guardar y comprobar un listado de eventos y dependiendo de si esta en local se consulta o  no en red.

## Keywords

Room, Coroutines, Firebase, LiveData, Result, MVVM, Clean architecture
## Screenshots or Video

https://user-images.githubusercontent.com/73607974/152394511-9c3b2938-7e14-4a22-b8e5-6dd9f990d5e9.mp4

## Objetivos

## Criterios de Evaluación
Módulo de Acceso a Datos: UT-3 y UT-4.
Modulo de PSP: UT-1, UT-2, UT-3, UT-4.
Módulo de PMDM: UT-1, UT-2, UT-3, UT-4, UT-5, UT-8.

2022-02-03 17:27 UTC, redondoM20 commented on app/src/main/java/com/jmperezra/avilaentapas/features/main/MainActivity.kt
> +    private val viewModel: EventListViewModel by viewModels()
¿Por que implementas el viewModel de eventos aqui si no se usa??

2022-02-03 17:33 UTC, redondoM20 commented on app/src/main/java/com/jmperezra/avilaentapas/features/events/domain/Models.kt
> +    val urlConatct:String,
No seria mejor urlContact??

2022-02-03 17:34 UTC, redondoM20 commented on app/src/main/java/com/jmperezra/avilaentapas/features/events/data/local/db/entities/Entities.kt
> +                organizerModel.urlConatct,
No seria mejor urlContact??

2022-02-03 17:45 UTC, redondoM20 approved these changes
En general esta bastante bien, solo he puesto algún comentario sin importancia 👌👌

2022-02-03 19:02 UTC, tijanidian commented on app/src/main/java/com/jmperezra/avilaentapas/features/main/MainActivity.kt
> +    private val viewModel: EventListViewModel by viewModels()
Cierto es, ya lo he solucionado.

2022-02-03 19:04 UTC, tijanidian commented on app/src/main/java/com/jmperezra/avilaentapas/features/events/domain/Models.kt
> +    val urlConatct:String,
Bien visto, solucionado.

2022-02-04 07:50 UTC, jmperezra commented on app/src/main/java/com/jmperezra/avilaentapas/features/main/MainActivity.kt
> +    private val viewModel: EventListViewModel by viewModels()
Muy bien @redondoM20 por el comentario.

2022-02-04 08:21 UTC, jmperezra requested changes
La PR en líneas generales está bien. 
Cosas que hay que mejorar:
1. Debemos seguir trabajando un poco más en las relaciones con Room.
2. Debemos seguir trabajando con la interacción en la UI (strings)
3. Namings.
Cosas que van muy bien:
1. Diseño de UI.
2. Lógica de la capa de repositorio: Repositorio, LocalSource, RemoteSource.
3. Lógica de la capa de presentación: Fragment, ViewModel.

2022-02-04 08:21 UTC, jmperezra commented on app/src/main/java/com/jmperezra/avilaentapas/features/events/presentation/EventViewHolder.kt
> +        bind.labelStartDate.text =view.context.getString(R.string.from_view)+eventModel.start
Concatena la cadena pasando como parámetro la fecha.

2022-02-04 08:21 UTC, jmperezra commented on app/src/main/java/com/jmperezra/avilaentapas/features/events/presentation/EventViewHolder.kt
> +        bind.labelEndDate.text =view.context.getString(R.string.until_view)+eventModel.end
Concatena la cadena pasando como parámetro la fecha.

2022-02-04 08:21 UTC, jmperezra commented on app/src/main/java/com/jmperezra/avilaentapas/features/events/presentation/EventViewHolder.kt
> +        bind.labelManagement.text= view.context.getString(R.string.organizer_view)+eventModel.organizerModel.name
Concatena la cadena pasando como parámetro el nombre.

2022-02-04 08:21 UTC, jmperezra commented on app/src/main/java/com/jmperezra/avilaentapas/features/events/presentation/EventsListFragment.kt
> +        viewModel.loadEvents()
Novedad: para la formación en liveData, hemos visto en clase que el viewModel.loadEents lo cargábamos en el onViewCreated porque era cuando la vista estaba creada. Bien, esta llamada no tiene mucho sentido aquí. En este caso, tiene más sentido que la metas en el bloque init del ViewModel y que pase a ser privada. El bloque init se ejecuta cuando se crea el ViewModel. Y el ViewModel se crea cuando el Fragment esté listo.
```
init{
  loadEvents()
}
```

2022-02-04 08:21 UTC, jmperezra commented on app/src/main/java/com/jmperezra/avilaentapas/features/events/presentation/EventsListFragment.kt
> +        viewModel.loadEvents()
Novedad: para la formación en liveData, hemos visto en clase que el viewModel.loadEents lo cargábamos en el onViewCreated porque era cuando la vista estaba creada. Bien, esta llamada no tiene mucho sentido aquí. En este caso, tiene más sentido que la metas en el bloque init del ViewModel y que pase a ser privada. El bloque init se ejecuta cuando se crea el ViewModel. Y el ViewModel se crea cuando el Fragment esté listo.
```
init{
  loadEvents()
}
```

2022-02-04 08:21 UTC, jmperezra commented on app/src/main/res/values/strings.xml
> +    <string name="from_view">Desde el &#160;</string>
uhhh esto se usa?? el formato no es correcto:
```
<string name="from_view">Desde el  %1$d</string>
```
Y en la vista debes usar:
```
getString(R.string.from_view, uistate.organizar.start) //por ejemplo.
```

2022-02-04 08:21 UTC, jmperezra commented on app/src/main/res/values/strings.xml
> +    <string name="until_view">Hasta el &#160;</string>
Lo mismo que antes.

2022-02-04 08:21 UTC, jmperezra commented on app/src/main/res/values/strings.xml
> +    <string name="organizer_view">Organizador: &#160;</string>
Lo mismo que antes.

2022-02-04 11:16 UTC, tijanidian commented on app/src/main/java/com/jmperezra/avilaentapas/features/events/data/EventDataRepository.kt
> +        return if (localEvents.getOrNull()?.isEmpty() == true) {
Solucionado.

2022-02-04 11:17 UTC, tijanidian commented on app/src/main/java/com/jmperezra/avilaentapas/features/events/data/local/db/EventDbLocalSource.kt
> +            val event = eventDao.findById(eventId)
Mucho mejor :)

2022-02-04 11:17 UTC, tijanidian commented on app/src/main/java/com/jmperezra/avilaentapas/features/events/data/local/db/dao/EventDao.kt
> +    @Query("SELECT * FROM events WHERE id= :tapaId LIMIT 1")
Gracias :)

2022-02-04 11:19 UTC, tijanidian commented on app/src/main/java/com/jmperezra/avilaentapas/features/events/data/local/db/EventDbLocalSource.kt
> +            ClearEvents()
Ups, no lo había visto :)

2022-02-04 11:20 UTC, tijanidian commented on app/src/main/java/com/jmperezra/avilaentapas/features/events/presentation/DetailEventActivity.kt
>          ActivityDetailEventBinding.inflate(layoutInflater)
Vale 🔢

2022-02-04 17:53 UTC, tijanidian commented on app/src/main/java/com/jmperezra/avilaentapas/features/events/data/EventDataRepository.kt
> +        return if (localEvents.getOrNull()?.isEmpty()!!) {
Solucionado

2022-02-04 18:02 UTC, jmperezra approved these changes

2022-02-04 18:02 UTC, merged