Sp04 mrobledore flow detail event
IESAM-DAM/avila-en-tapas pull request #91
Opened 2022-02-04 19:03 UTC by redondoM20

## Description de la tarea

Se pide completar el detalle de un evento con el flujo completo.

## ¿Cómo se ha implementado?

Se piden los datos a Room y si no se encuentra nada se recogerán de Firebase y se guardaran en el Room. Además, se ha implementado la función de compartir (Aunque no del todo) y los hipervínculos con la web de información del evento. También se han ajustado algunos detalles del diseño

## Keywords

EventDataRepository, Share, Html...

## Screenshots or Video

https://user-images.githubusercontent.com/91340559/152587492-d2cd3bb3-97c1-4933-8238-57a3a8be94e1.mp4

## Objetivos

## Criterios de Evaluación

2022-02-07 11:30 UTC, jmperezra requested changes
Hola Marcos, hay que corregir algunas cosillas. Te las he dejado como comentarios.

2022-02-07 11:30 UTC, jmperezra commented on app/src/main/java/com/jmperezra/avilaentapas/features/events/data/EventDataRepository.kt
> +            fetchEvent(eventId)
Vuelves a llamar a la misma función?? porqué no devuelves remoteEvents??

2022-02-07 11:30 UTC, jmperezra commented on app/src/main/java/com/jmperezra/avilaentapas/features/events/presentation/DetailEventActivity.kt
> +        bind.customToolbar.mainBar.background.alpha = 128
Esto hay que hacelo con styles, lo veremos.

2022-02-07 11:30 UTC, jmperezra commented on app/src/main/java/com/jmperezra/avilaentapas/features/events/presentation/DetailEventActivity.kt
> +        val shareIntent = Intent.createChooser(sendIntent, "Avila en Tapas")
Pasa el "Avila en Tapas" al fichero R.string

2022-02-07 11:30 UTC, jmperezra commented on app/src/main/java/com/jmperezra/avilaentapas/features/events/presentation/EventViewHolder.kt
> +            val intent = Intent(view.context, DetailEventActivity::class.java)
Esto hemos visto en clase otra alternativa. Lo puedes encontrar en el object companion de la actividad de detalle de tapas.

2022-02-07 11:30 UTC, jmperezra commented on app/src/main/res/layout/event_list_fragment.xml
> +        android:layout_height="wrap_content"
mejor match para poder hacer scroll con los dedos en todas las pantallas.

2022-02-07 12:07 UTC, mesteban10 approved these changes
Estoy de acuerdo con los cambios propuestos por chema, yo te he dejado un comentario con un pequeño cambio que puedes realizar, revisalo :)

2022-02-07 12:07 UTC, mesteban10 commented on app/src/main/res/layout/view_custom_toolbar.xml
> +    android:elevation="8dp"/>
Puedes extraer el valor en un @dimens.

2022-02-09 17:26 UTC, mesteban10 approved these changes
Te he dajado un comentario, ya que has actualizado una librería y esto debería realizarse en otra tarea. Por lo demás el código esta bien 👍

2022-02-09 17:26 UTC, mesteban10 commented on build.gradle
> +        classpath 'com.android.tools.build:gradle:7.1.1'
Esto deberíamos de actualizarlo en otra Issue dedicada a ello :)

2022-02-09 19:58 UTC, jmperezra requested changes
Marcos, no acabo de ver la parte de la gestión de datos entre local y remoto.
Si obtengo de local, devuelvo, sino, pido a remoto, guardo en base de datos y devuelvo (si quieres puedes devolver de local). No entiendo muy bien la gestión de pedir de remoto un único evento, pides todos, luego guardas todos, luego pides uno... no lo veo.

2022-02-09 19:58 UTC, jmperezra commented on app/src/main/java/com/jmperezra/avilaentapas/features/events/data/EventDataRepository.kt
> +            val remoteEvents = remoteSource.getEvents()
Marcos, en esta ocasión lo que hay que hacer es obtener un único evento y persistir sólo ese evento. 
```
remote.getEvent(eventId)
```

2022-02-09 19:58 UTC, jmperezra commented on app/src/main/java/com/jmperezra/avilaentapas/features/events/data/EventDataRepository.kt
> +                localSource.saveEvents(it)
guardamos sólo un evento, localsource.saveEvent(eventModel)

2022-02-09 19:58 UTC, jmperezra commented on app/src/main/java/com/jmperezra/avilaentapas/features/events/data/EventDataRepository.kt
> +            remoteSource.getEvent(eventId)
No entiendo porque ahora vuelves a pedir a remoto un único evento.

2022-02-09 19:58 UTC, jmperezra commented on app/src/main/java/com/jmperezra/avilaentapas/features/events/data/remote/EventDbRemoteSource.kt
> +        var event = EventModel("","","","","","", FileModel("","",), OrganizerModel("","","",  ""))
mmm no entiendo porque inicializar el evento con valores. Créalo nulo y al final de la función devuelves la tapa si tiene datos y si es nula, devuelves un error.

2022-02-09 19:58 UTC, jmperezra commented on app/src/main/java/com/jmperezra/avilaentapas/features/events/data/remote/EventDbRemoteSource.kt
> +        var event = EventModel("","","","","","", FileModel("","",), OrganizerModel("","","",  ""))
En la parte de TapasDbRemoteSource hay un ejemplo

2022-02-10 17:40 UTC, jmperezra approved these changes
Ahora si Marcos, mmm a ver si trabajamos algo más de datos para seguir viendo cosas.
A mergear!

2022-02-10 18:19 UTC, merged