Pantallas de error de y listado vacío de eventos
IESAM-DAM/avila-en-tapas pull request #99
Opened 2022-02-10 17:01 UTC by tijanidian

## Description de la tarea

Se pide implementar una nueva feature que muestre una vista cuando ocurre un error
y otra vista cuando el listado de eventos esté vacío.

## ¿Cómo se ha implementado?

He creado una nueva feature llamada "error" donde he creado otra clase ErrorView, 
que extiende de LinearLayout, luego he hecho la lógica para poder mostrar la imagen y texto.
Para el listado de eventos he creado una lógica para comprobar si eventos es vacío para mostrar la CustomView.
## Keywords
LinearLayout, CustomView

## Screenshots or Video

https://user-images.githubusercontent.com/73607974/153457999-5aaad0df-1d7f-477a-9743-13771019727c.mp4

2022-02-10 17:35 UTC, jmperezra commented on app/src/main/res/layout/view_error.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
Métele el margen por defecto: both_spacing

2022-02-10 18:09 UTC, JavierManc commented on app/src/main/java/com/jmperezra/avilaentapas/features/events/data/remote/EventDbRemoteSource.kt
> +                .child("eventss")
¿Por qué has añadido una "s" a events?

2022-02-10 18:53 UTC, tijanidian commented on app/src/main/java/com/jmperezra/avilaentapas/features/events/presentation/EventsListFragment.kt
> +            loadErrorLoading(
Solucionado

2022-02-10 18:54 UTC, tijanidian commented on app/src/main/res/layout/view_error.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
Le he metido margen también a al texto y a la imagen

2022-02-11 19:20 UTC, jmperezra requested changes
Hay algunos conceptos que se deben corregir.

2022-02-11 19:20 UTC, jmperezra commented on app/src/main/res/layout/fragment_event_list.xml
> +    <androidx.recyclerview.widget.RecyclerView
Tijani, vamos a corregir cosillas de otras PR. En este caso, el ConstraintLayout no es necesario, te vale con el recyclerview

2022-02-11 19:20 UTC, jmperezra commented on app/src/main/java/com/jmperezra/avilaentapas/features/events/presentation/EventsListFragment.kt
> +        (requireActivity() as MainActivity).showEmptyView()
Te explico en el código lo que te quería decir antes. En el fragmento dejas claro que quieres mostrar una vista con un mensaje de lista vacía, para ello lo llamamos showEmptyListView. Ahora, lo que no podemos hacer, es meter el contenido en el activity, es decir, aquí deberías hacer la siguiente llamada:
```
(requireActivity() as MainActivity).showStateView(StateView.UiState(
                getString(R.string.label_emptylist),
                ContextCompat.getDrawable(this, R.drawable.ic_emptylist)
            )
```
Recuerda que no te hace falta las !! y el recurso es el svg de emptylist.

2022-02-11 19:20 UTC, jmperezra commented on app/src/main/java/com/jmperezra/avilaentapas/features/events/presentation/EventsListFragment.kt
> +        (requireActivity() as MainActivity).hideEmptyView()
Aqui sería: 
        (requireActivity() as MainActivity).hideStateView()

2022-02-11 19:20 UTC, jmperezra commented on app/src/main/java/com/jmperezra/avilaentapas/features/events/presentation/EventsListFragment.kt
> +        showEmptyListView()
Y aquí lo mismo, dejas claro que quieres mostrar un error, correcto. Ahora debes llamar al método del MainActivity que te permite mostrar el error:
```
(requireActivity() as MainActivity).showStateView(StateView.UiState(
                getString(R.string.label_common_error),
                ContextCompat.getDrawable(this, R.drawable.ic_error)
            )
```

La idea de todo esto, es dejar bien claro lo que se quiere hacer en el fragmento y luego visualizarlo con métodos comunes en el MainActivity.

2022-02-11 19:25 UTC, tijanidian commented on app/src/main/res/layout/fragment_event_list.xml
> +        android:id="@+id/error_view"
creo que eso no se ha actualizado, ya lo había cambiado al activity_main

2022-02-12 12:44 UTC, jmperezra approved these changes
Ahora si Tijani, hago merge de la PR.

2022-02-12 12:45 UTC, merged